/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on May 16, 2012, 3:18:04 PM
 */
package tm1ipchanger;

/**
 *
 * @author tom.saxton-howes
 */
public class GUI extends java.awt.Frame {

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfiguredTextField = new java.awt.TextField();
        ConfiguredLabel = new java.awt.Label();
        LocationTextField = new java.awt.TextField();
        LocationLabel = new java.awt.Label();
        CurrentTextField = new java.awt.TextField();
        CurrentLabel = new java.awt.Label();
        ChangeButton = new java.awt.Button();
        HelpButton = new java.awt.Button();

        setBackground(new java.awt.Color(255, 205, 156));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocationRelativeTo(this);
        setMinimumSize(new java.awt.Dimension(350, 200));
        setTitle("IP Changer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConfiguredTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ConfiguredTextField.setEditable(false);
        add(ConfiguredTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 200, 30));

        ConfiguredLabel.setText("Configured IP");
        add(ConfiguredLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, -1));

        LocationTextField.setName("LocationTextField"); // NOI18N
        LocationTextField.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                LocationTextFieldTextValueChanged(evt);
            }
        });
        add(LocationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 200, 30));

        LocationLabel.setName(""); // NOI18N
        LocationLabel.setText("Config Location");
        add(LocationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        CurrentTextField.setName(""); // NOI18N
        add(CurrentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 200, 30));
        CurrentTextField.getAccessibleContext().setAccessibleName("");

        CurrentLabel.setText("Current IP");
        add(CurrentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, -1));

        ChangeButton.setLabel("Change");
        ChangeButton.setName(""); // NOI18N
        ChangeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeButtonMouseClicked(evt);
            }
        });
        add(ChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        HelpButton.setLabel("Help");
        HelpButton.setName(""); // NOI18N
        HelpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpButtonMouseClicked(evt);
            }
        });
        add(HelpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void LocationTextFieldTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_LocationTextFieldTextValueChanged
        TM1IPChanger.findIP(LocationTextField.getText(),
                TM1IPChanger.getPmpsvcLocation(), 
                TM1IPChanger.getFmpsvcLocation());
    }//GEN-LAST:event_LocationTextFieldTextValueChanged

    private void HelpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpButtonMouseClicked
        Help helpmsg = new Help(this,true);
        helpmsg.setVisible(true);
    }//GEN-LAST:event_HelpButtonMouseClicked

    private void ChangeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeButtonMouseClicked
        TM1IPChanger.updateconfig(CurrentTextField.getText(),
                ConfiguredTextField.getText(),
                TM1IPChanger.getConfigLocation(),
                TM1IPChanger.getPmpsvcLocation(),
                TM1IPChanger.getFmpsvcLocation());
    }//GEN-LAST:event_ChangeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    public void setConfigureIP(String IP){
        if (IP != null){
            ConfiguredTextField.setEnabled(true);
            ConfiguredTextField.setText(IP);
            ConfiguredTextField.setEnabled(false);
        }
        
    }
    public String getConfiguredIP(){
        return ConfiguredTextField.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button ChangeButton;
    private java.awt.Label ConfiguredLabel;
    private java.awt.TextField ConfiguredTextField;
    private java.awt.Label CurrentLabel;
    private java.awt.TextField CurrentTextField;
    private java.awt.Button HelpButton;
    private java.awt.Label LocationLabel;
    private java.awt.TextField LocationTextField;
    // End of variables declaration//GEN-END:variables
}
