/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Help.java
 *
 * Created on May 28, 2012, 9:58:06 AM
 */
package tm1ipchanger;

/**
 *
 * @author tom.saxton-howes
 */
public class Help extends java.awt.Dialog {

    /** Creates new form Help */
    public Help(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        OkButton = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        textArea1.setEditable(false);
        textArea1.setText("If the Confgiured IP is blank enter the location of your pmpsvc and fmpsvc\nconfig files\n\nOnce the Configured IP is displayed enter your IP in the current IP field\nand press change. once the change has completed a message box will\nconfirm the change has been made\n\nto find your current IP address follow these steps\n1. click on the start menu\n2. go to all programs\n3. Accessories\n4. command prompt\n5. type ipconfig and press return\n6. your ip address is displayed next to IP Address it should appear like\n192.168.0.135\n\nHave a problem contact the Budgeting Solutions Support desk\nsupport@budgetingsolutions.co.uk");
        add(textArea1, java.awt.BorderLayout.CENTER);

        OkButton.setLabel("OK");
        OkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OkButtonMouseClicked(evt);
            }
        });
        OkButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OkButtonKeyPressed(evt);
            }
        });
        add(OkButton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void OkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkButtonMouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_OkButtonMouseClicked

    private void OkButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OkButtonKeyPressed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_OkButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Help dialog = new Help(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button OkButton;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
